In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x = np.array([23,46,43,12,34])
y = np.array([21,45,76,94,23])

In [3]:
print(x)
print(y)

[23 46 43 12 34]
[21 45 76 94 23]


In [4]:
y=y.reshape((-1,1))

In [5]:
print(y)

[[21]
 [45]
 [76]
 [94]
 [23]]


In [6]:
model =LinearRegression()

In [7]:
model.fit(x,y)

ValueError: Expected 2D array, got 1D array instead:
array=[23 46 43 12 34].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.